spring.application.name=reminder-service
server.port=8083

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

# Embedded Artemis JMS Configuration
spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false
spring.jms.pub-sub-domain=false

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.listener.auto-startup=false
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false

logging.level.com.bridgelabz.reminder=DEBUG
