server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-auth-route
          uri: lb://user-auth-service
          predicates:
            - Path=/auth/**, /users/**, /user/**
        - id: notes-route
          uri: lb://notes-service
          predicates:
            - Path=/notes/**, /labels/**
        - id: reminder-route
          uri: lb://reminder-service
          predicates:
            - Path=/reminders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
